### ISSUE TITLE
Bug while comparing floats

### ISSUE THREAD

**Issue by SSMellow** [coduo/php-matcher#158] opened 2019-07-31 10:16 UTC
While comparing two arrays, and in both there is same float value, matcher does not match. 
F.E. $payload1 = ['number' => 123.45, 'key' => 'random']
$payload2 = ['number' => 123.45, 'key' => 'random']

Error - "123.45" does not match "123.45". (Exception)

**Comment by teklakct** [comment] 2019-08-07 19:25
I can't reproduce this. @SSMellow please provide a full working code example

**Comment by norzechowicz** [comment] 2019-08-07 20:08
Closing since I wasn't able to reproduce it as well. @SSMellow please open a PR with failing tests case for this issue, then we will try to help you

**Closed by norzechowicz** 2019-08-07 20:08 UTC
